language: java

jdk:
 - oraclejdk8

services:
 - postgresql

before_script:
  - psql -c 'create database perpus;' -U postgres

before_install:
 - chmod +x mvnw

deploy:
 provider: heroku
 api-key:
  secure: $HEROKU_API_KEY
 app: springboot-perpustakaan-api


